const content = `{
  "name": "nice-dir-yo",
  "version": "1.0.0",
  "description": "A new app.",
  "main": "dist/app.bundle.js",
  "scripts": {
    "start": "ts-node ./build/server.ts",
    "test": "jest --collectCoverage",
    "build": "webpack --config ./build/webpack.prod.config.ts"
  },
  "author": "your_name <your_email>",
  "dependencies": {
    "@types/node": "15.6.1",
    "@types/react": "^17.0.8",
    "@types/react-dom": "^17.0.5",
    "@types/react-router-dom": "^5.1.7",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-router-dom": "^5.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.14.3",
    "@babel/preset-env": "^7.14.4",
    "@babel/preset-typescript": "^7.13.0",
    "@testing-library/jest-dom": "^5.12.0",
    "@testing-library/react": "^11.2.7",
    "@types/express": "^4.17.12",
    "@types/friendly-errors-webpack-plugin": "^0.1.2",
    "@types/html-webpack-plugin": "^3.2.3",
    "@types/jest": "^25.2.3",
    "@types/webpack": "^4.41.13",
    "@types/webpack-dev-middleware": "^3.7.1",
    "@types/webpack-env": "^1.15.2",
    "@types/webpack-hot-middleware": "^2.25.3",
    "@types/webpack-merge": "^4.1.5",
    "@typescript-eslint/eslint-plugin": "^4.26.0",
    "@typescript-eslint/parser": "^4.26.0",
    "babel-jest": "^27.0.2",
    "babel-preset-react-app": "^10.0.0",
    "clean-webpack-plugin": "^3.0.0",
    "css-loader": "^5.2.4",
    "eslint": "^7.27.0",
    "eslint-config-airbnb": "^18.2.1",
    "eslint-plugin-import": "^2.23.4",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-react": "^7.24.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "express": "^4.17.1",
    "file-loader": "^6.0.0",
    "fork-ts-checker-webpack-plugin": "^4.1.4",
    "friendly-errors-webpack-plugin": "^1.7.0",
    "html-webpack-plugin": "^4.3.0",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^26.0.1",
    "jest-environment-jsdom-fourteen": "^1.0.1",
    "sass": "^1.34.0",
    "sass-loader": "^8.0.2",
    "style-loader": "^1.2.1",
    "ts-loader": "^7.0.4",
    "ts-node": "^10.0.0",
    "typescript": "^4.3.2",
    "url-loader": "^4.1.0",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.11",
    "webpack-dev-middleware": "^3.7.2",
    "webpack-hot-middleware": "^2.25.0",
    "webpack-merge": "^4.2.2"
  }
}
`;

export default content;
