const content = `{
    "name": "",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "scripts": {
      "start": "ts-node ./build/server.ts",
      "test": "jest --collectCoverage",
      "build": "webpack --config ./build/webpack.prod.config.ts"
    },
    "author": "",
    "dependencies": {
      "@types/node": "12.12.6",
      "@types/react": "^16.9.35",
      "@types/react-dom": "^16.9.8",
      "@types/react-router-dom": "^5.1.5",
      "dotenv": "^8.2.0",
      "mobx": "^6.0.1",
      "mobx-react-lite": "^3.0.1",
      "react": "^16.13.1",
      "react-dom": "^16.13.1",
      "react-router-dom": "^5.2.0"
    },
    "devDependencies": {
      "@babel/core": "^7.9.6",
      "@babel/preset-env": "^7.9.6",
      "@babel/preset-typescript": "^7.9.0",
      "@testing-library/jest-dom": "^5.8.0",
      "@testing-library/react": "^10.0.4",
      "@types/express": "^4.17.6",
      "@types/friendly-errors-webpack-plugin": "^0.1.2",
      "@types/html-webpack-plugin": "^3.2.3",
      "@types/jest": "^25.2.3",
      "@types/webpack": "^4.41.13",
      "@types/webpack-dev-middleware": "^3.7.1",
      "@types/webpack-env": "^1.15.2",
      "@types/webpack-hot-middleware": "^2.25.3",
      "@types/webpack-merge": "^4.1.5",
      "@typescript-eslint/eslint-plugin": "^3.0.0",
      "@typescript-eslint/parser": "^3.0.0",
      "babel-jest": "^26.0.1",
      "babel-preset-react-app": "^9.1.2",
      "clean-webpack-plugin": "^3.0.0",
      "css-loader": "^3.5.3",
      "eslint": "^7.1.0",
      "eslint-config-airbnb": "^18.1.0",
      "eslint-plugin-import": "^2.20.2",
      "eslint-plugin-jsx-a11y": "^6.2.3",
      "eslint-plugin-react": "^7.20.0",
      "eslint-plugin-react-hooks": "^4.1.2",
      "express": "^4.17.1",
      "file-loader": "^6.0.0",
      "fork-ts-checker-webpack-plugin": "^4.1.4",
      "friendly-errors-webpack-plugin": "^1.7.0",
      "html-webpack-plugin": "^4.3.0",
      "identity-obj-proxy": "^3.0.0",
      "jest": "^26.0.1",
      "jest-environment-jsdom-fourteen": "^1.0.1",
      "node-sass": "^4.14.1",
      "open": "^7.0.4",
      "sass-loader": "^8.0.2",
      "style-loader": "^1.2.1",
      "ts-loader": "^7.0.4",
      "ts-node": "^8.10.1",
      "typescript": "^3.9.3",
      "url-loader": "^4.1.0",
      "webpack": "^4.43.0",
      "webpack-cli": "^3.3.11",
      "webpack-dev-middleware": "^3.7.2",
      "webpack-hot-middleware": "^2.25.0",
      "webpack-merge": "^4.2.2"
    }
  }
`;

export default content;
